sonar.projectKey=SamuelPuerta_Transcription-service
sonar.organization=samuelpuerta

sonar.projectName=Transcription-service
sonar.projectVersion=0.1.0

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.python.version=3.13

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=xunit-reports/xunit-result.xml

sonar.exclusions=**/__pycache__/**,**/*.pyc,**/.venv/**,**/site-packages/**
