from typing import Optional, Protocol
from src.domain.entities.call_processing_entity import CallProcessingEntity

class CallProcessing(Protocol):
    async def get_by_id(self, id: str) -> Optional[CallProcessingEntity]: ...
    async def create(self, entity: CallProcessingEntity) -> None: ...
    async def update(self, entity: CallProcessingEntity) -> None: ...
    async def delete(self, id: str) -> None: ...
    async def increment_total_files(self, batch_id: str, delta: int = 1) -> None: ...
    async def mark_as_started(self, batch_id: str) -> None: ...
    async def increment_completed(self, batch_id: str, delta: int = 1) -> None: ...
    async def increment_failed(self, batch_id: str, delta: int = 1) -> None: ...
    async def check_completion(self, batch_id: str) -> str: ...
