from typing import Protocol
from src.domain.entities.call_processing_entity import CallProcessingEntity
from src.domain.ports.infrastructure.persistence.mongo_generic import MongoGeneric

class CallProcessing(MongoGeneric[CallProcessingEntity], Protocol):
    async def increment_total_files(self, batch_id: str, delta: int = 1) -> None: ...
    async def mark_as_started(self, batch_id: str) -> None: ...
    async def increment_completed(self, batch_id: str, delta: int = 1) -> None: ...
    async def increment_failed(self, batch_id: str, delta: int = 1) -> None: ...
    async def check_completion(self, batch_id: str) -> str: ...
