from typing import Optional, Protocol
from src.domain.entities.files_evaluation_enrichment_entity import FilesEvaluationEnrichmentEntity
from src.domain.entities.files_processing_entity import FilesProcessingEntity
from src.domain.entities.files_xlsx_enrichment_entity import FilesXlsxEnrichmentEntity
from src.domain.ports.infrastructure.persistence.mongo_generic import MongoGeneric

class FilesProcessing(MongoGeneric[FilesProcessingEntity], Protocol):
    async def create(self, entity: FilesProcessingEntity) -> Optional[str]: ...
    async def apply_xlsx_enrichment(self, file_id: str, enrichment: FilesXlsxEnrichmentEntity) -> None: ...
    async def apply_evaluation_enrichment(self, file_id: str, enrichment: FilesEvaluationEnrichmentEntity) -> None: ...
    async def get_by_blob_url(self, blob_url: str) -> Optional[FilesProcessingEntity]: ...
    async def mark_as_processing(self, file_id: str) -> None: ...
    async def set_transcription(self, file_id: str, transcription: str) -> None: ...
    async def mark_as_completed(self, file_id: str) -> None: ...
    async def mark_as_failed(self, file_id: str, error_message: str | None = None) -> None: ...
