from typing import Generic, Optional, Protocol, TypeVar

T = TypeVar('T')


class MongoGeneric(Protocol[T]):
    async def get_by_id(self, id: str) -> Optional[T]: ...
    async def create(self, entity: T) -> None: ...
    async def update(self, entity: T) -> None: ...
    async def delete(self, id: str) -> None: ...
