from typing import Protocol

class AIGateway(Protocol):
    async def chat_completion(self, system_prompt: str, user_prompt: str) -> str: ...
    async def create_transcription(self, audio_uri: str) -> str: ...
    async def get_transcription_status(self, transcription_id: str) -> str: ...
    async def get_transcription_result(self, transcription_id: str) -> str: ...
